../../pyodbc.pyi,sha256=cLuLanSS0Vry9aUUvn-i1lpDxHiDcMQwQFypGWqD__E,13127
pyodbc-4.0.34.dist-info/INSTALLER,sha256=zuuue4knoyJ-UwPPXg8fezS7VCrXJQrAP7zeNuwvFQg,4
pyodbc-4.0.34.dist-info/LICENSE.txt,sha256=mFnIV3DJG3hmsPdpyTjjbWTQJgFBtSm5R7Tq2WiD6rQ,868
pyodbc-4.0.34.dist-info/METADATA,sha256=9OvmhDABSFHthoXvVk6wdB2IT48YRKR76m_UntEfUBE,2719
pyodbc-4.0.34.dist-info/RECORD,,
pyodbc-4.0.34.dist-info/REQUESTED,sha256=47DEQpj8HBSa-_TImW-5JCeuQeRkm5NMpJWZG3hSuFU,0
pyodbc-4.0.34.dist-info/WHEEL,sha256=W26pYN7HLsBT1jrDSL9udgf_mdNKJmYmL23sIP-FcgM,102
pyodbc-4.0.34.dist-info/direct_url.json,sha256=MzUAzg_8XSieyRi5EWjx8obvfuCr838zX9n63OStcj8,105
pyodbc-4.0.34.dist-info/top_level.txt,sha256=30jvYcCul6_wA26OT5c068GAHzqQLpd9WfQ0mSSsDTU,7
pyodbc.cp310-win_amd64.pyd,sha256=mIis1Csc08W_sWOSpMtnE-VLqz2RK_qc0uzaM1yfKDg,131584
